volumes:
  node_modules:
services:
  front-end:
    build:
      context: .
      dockerfile: Containerfile
    restart: on-failure:3
    ports:
      - "3000:3000"
    volumes:
      - .:/app:z
      - node_modules:/app/node_modules:z
